spring:
  application:
    name: TripService
  datasource:
    url: jdbc:postgresql://localhost:5432/trip_creation
    password: 1234
    driver-class-name: org.postgresql.Driver
    username: apple

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

server:
  port: 7070