spring:
  application:
    name: AuthenticationService

  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    password: 1234
    driver-class-name: org.postgresql.Driver
    username: apple

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

  main:
    allow-circular-references: true