
spring:
  application:
    name: AuthenticationService
  datasource:
    db-kind: postgres
    url: jdbc:postgresql://localhost:5432/jwt_security
    password: 1234
    driver-class-name: org.postgresql.Driver
    username: apple

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

  main:
    allow-circular-references: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 9898


management:
  tracing:
    sampling:
      probability: 1.0