spring:
  application:
    name: demo
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090

management:
  tracing:
    sampling:
      probability: 1.0
