eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        - id: authentication
          uri: http://localhost:9898
          predicates:
            - Path=/auth/**

        - id: tripService
          uri: http://localhost:7070
          predicates:
            - Path=/trip/**
          filters:
            - AuthenticationFilter
