eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: demo
          uri: http://localhost:8090
          predicates:
            - Path=/demo/**
          filters:
            - AuthenticationFilter

        - id: authentication
          uri: http://localhost:9898
          predicates:
            - Path=/auth/**

management:
  tracing:
    sampling:
      probability: 1.0