eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        discovery:
          locator:
            enabled: true
        routes:
          - id: students
            uri: http://localhost:8090
            predicates:
              - Path=/demo/**

management:
  tracing:
    sampling:
      probability: 1.0